version: '3'

services:
  
  app:
    build: .
    container_name: micro-codeflix
    entrypoint: ./.docker/entrypoint.sh
    tty: true
    volumes:
      - .:/home/node/app
    ports:
      - 3002:3000
    